AnlautfuchsBundle\Entity\Companion:
    type: entity
    table: companion
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        type:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
        sorting:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
        unlockedOnGameWon:
            type: boolean
            nullable: false
            comment: ''
    manyToOne:
        neededLevelId:
            targetEntity: Levels
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                needed_level_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
