<?php

namespace AnlautfuchsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CharacterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CharacterRepository extends EntityRepository
{

    public function getFirstRowCharacters(){
        return $this->getCharactersForRow(0);
    }

    public function getSecondRowCharacters(){
        return $this->getCharactersForRow(1);
    }

    private function getCharactersForRow($row){
        $query = $this->createQueryBuilder('char')
            ->where('char.row = :rowId')
            ->setParameter('rowId', $row)
            ->getQuery();

        return $query->getResult();
    }
}
