<?php

namespace AnlautfuchsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{

    public function checkUser($username, $password){
        $user = $this->getUser($username);

        if(!$user){
            return -1;
        }

        if(!$this->checkPassword($username, $password)){
            return -2;
        }

        return $user;
    }

    public function getUser($username){
        return $this->findOneByName($username);
    }

    public function checkPassword($username, $password){

        $query = $this->createQueryBuilder('u')
            ->where('u.name = :username AND u.password = :password')
            ->setParameter('username', $username)
            ->setParameter('password', $password)
            ->getQuery();

        $user = $query->getOneOrNullResult();

        if($user){
            return true;
        }

        return false;
    }
}
